# Generated by Django 2.2.4 on 2019-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('vFullVegan', models.BooleanField()),
                ('vVege', models.BooleanField()),
                ('vMeat', models.BooleanField()),
                ('vFish', models.BooleanField()),
                ('vEgg', models.BooleanField()),
                ('vBird', models.BooleanField()),
                ('vMilk', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='productSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdId', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('material', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('subCategory', models.CharField(max_length=50)),
                ('simProduct1', models.SlugField()),
                ('simProduct2', models.SlugField()),
                ('simProduct3', models.SlugField()),
                ('vFullVegan', models.BooleanField()),
                ('vVege', models.BooleanField()),
                ('vMeat', models.BooleanField()),
                ('vFish', models.BooleanField()),
                ('vEgg', models.BooleanField()),
                ('vBird', models.BooleanField()),
                ('vMilk', models.BooleanField()),
            ],
        ),
    ]
