# Generated by Django 2.2.4 on 2019-08-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bvserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlist',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productspec',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
